// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOiQREjdOAw8CjR_ojkyOehoBuGGycGBw',
    appId: '1:862742994362:web:464fe259aaa2b0bbd89183',
    messagingSenderId: '862742994362',
    projectId: 'dicoding-ditonton-a2992',
    authDomain: 'dicoding-ditonton-a2992.firebaseapp.com',
    storageBucket: 'dicoding-ditonton-a2992.appspot.com',
    measurementId: 'G-X8VF245DRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXqTR4KwPb8NrPjFcrPhXngFIFcPoKgUM',
    appId: '1:862742994362:android:fc21be39cbcfa1d7d89183',
    messagingSenderId: '862742994362',
    projectId: 'dicoding-ditonton-a2992',
    storageBucket: 'dicoding-ditonton-a2992.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYXnfHEGXkpnaF02cDFu0wNpN6S-Zxqc8',
    appId: '1:862742994362:ios:c4ec917c14fc1b1fd89183',
    messagingSenderId: '862742994362',
    projectId: 'dicoding-ditonton-a2992',
    storageBucket: 'dicoding-ditonton-a2992.appspot.com',
    iosBundleId: 'com.example.ditontonExpertCourse',
  );
}
